### ISSUE TITLE
When will the codes be released?

### ISSUE THREAD

**Issue by anse3832** [volflow/DeFlow#1]
I'm looking forward to the DeFlow codes.
Thanks.

**Comment by volflow** [comment]
Hi anse3832,

thank you for the interest in DeFlow. 
Part of the code was just released and the missing parts (training on DPED-RWSR dataset and the downstream ESRGAN models) will be added shortly.

Best,
Valentin

**Comment by anse3832** [comment]
Thanks for your fast reply.
However, I can't find any bash file for downloading the datasets and for training the models.
(For example, get-AIM-RWSR-train.sh, get-NTIRE-RWSR-train.sh, get-DeFlow-models.sh, and so on)

**Comment by volflow** [comment]
Oops, I forgot to push those. They are online now :)
Thanks for letting me know!

**Comment by anse3832** [comment]
Sorry for bothering you.
When I tried to run get-NTIRE-RWSR-val.sh, it seems that there is no python file named as 'create_DeFlow_train_dataset.py'

**Comment by volflow** [comment]
No problem and thank you for letting me know :)
I forgot to add the the `.py` file (the dataset folder is in the .gitignore). It should now be online.
Let me know if you run into any other problems!

**Comment by anse3832** [comment]
Every code seems to work well.
However, when I tried to run "translate.py" using the NTIRE-RWSR dataset, it showed errors.
(It works well in the AIM-RWSR dataset)

command in terminal
CUDA_VISIBLE_DEVICES=-1 python translate.py -opt DeFlow-NTIRE-RWSR.yml -model_path ../trained_models/DeFlow_models/DeFlow-NTIRE-RWSR-100k.pth -source_dir ../datasets/NTIRE-RWSR/Corrupted-tr-y/4x/ -out_dir ../datasets/NTIRE-RWSR/Corrupted-tr-y/4x_degraded/ 


error messages
Traceback (most recent call last):
  File "translate.py", line 55, in <module>
    zs, nll = model.get_encode_z_and_nll(lq=lq, gt=gt, y_label=labels, lr_enc=lr_enc, add_gt_noise=add_gt_noise, epses=[])
  File "/mnt/workspace/anse/code/pytorch/USR/DeFlow/codes/models/SRFL_Glow_model.py", line 208, in get_encode_z_and_nll
    z, nll, _ = self.netG(gt=gt, lr=lq, reverse=False, epses=epses, y_label=y_label, add_gt_noise=add_gt_noise, lr_enc=lr_enc)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/parallel/data_parallel.py", line 143, in forward
    return self.module(*inputs, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/mnt/workspace/anse/code/pytorch/USR/DeFlow/codes/models/modules/RRDBGlowNet_arch.py", line 76, in forward
    return self.normal_flow(gt, lr, epses=epses, lr_enc=lr_enc, add_gt_noise=add_gt_noise, step=step, y_onehot=y_label)
  File "/mnt/workspace/anse/code/pytorch/USR/DeFlow/codes/models/modules/RRDBGlowNet_arch.py", line 123, in normal_flow
    epses, logdet = self.flowUpsamplerNet(rrdbResults=lr_enc, gt=z, logdet=logdet, reverse=False, epses=epses, y_onehot=y_onehot)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/mnt/workspace/anse/code/pytorch/USR/DeFlow/codes/models/modules/FlowUpsamplerNet.py", line 351, in forward
    z, logdet = self.encode(gt, rrdbResults, logdet=logdet, epses=epses, y_onehot=y_onehot)
  File "/mnt/workspace/anse/code/pytorch/USR/DeFlow/codes/models/modules/FlowUpsamplerNet.py", line 400, in encode
    fl_fea, logdet = layer(fl_fea, logdet, reverse=reverse)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/mnt/workspace/anse/code/pytorch/USR/DeFlow/codes/models/modules/flow.py", line 203, in forward
    output = squeeze2d(input, self.factor)  # Squeeze in forward
  File "/mnt/workspace/anse/code/pytorch/USR/DeFlow/codes/models/modules/flow.py", line 172, in squeeze2d
    assert H % factor == 0 and W % factor == 0, "{}".format((H, W, factor))
AssertionError: (87, 127, 2)

Could you give the correct command for "Generating Synthetic Dataset for Downstream Tasks" using the NTIRE-RWSR dataset?

**Comment by anse3832** [comment]
All the codes works well and I can reproduce the results.
I'm looking forward to the detail methods of "Training the downstream ESRGAN models"
Thanks for your help!
